"""empty message

Revision ID: f5581b03d4ab
Revises: 
Create Date: 2022-11-08 18:13:11.924301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5581b03d4ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Fish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('species', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Fish')
    # ### end Alembic commands ###
